
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FROM NAME SELECT WHEREx : SELECT\n         | FROM\n         | WHERE\n         | NAMEtabla : NAME'
    
_lr_action_items = {'SELECT':([0,],[2,]),'FROM':([0,],[3,]),'WHERE':([0,],[4,]),'NAME':([0,],[5,]),'$end':([1,2,3,4,5,],[0,-1,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'x':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> x","S'",1,None,None,None),
  ('x -> SELECT','x',1,'p_expression_select','calculator.py',49),
  ('x -> FROM','x',1,'p_expression_select','calculator.py',50),
  ('x -> WHERE','x',1,'p_expression_select','calculator.py',51),
  ('x -> NAME','x',1,'p_expression_select','calculator.py',52),
  ('tabla -> NAME','tabla',1,'p_expression_name','calculator.py',56),
]
