reserved = {
#ENGLISH RESERVED WORDS
    'SELECT' : 'SELECT',
    'FROM' : 'FROM',
    'WHERE' : 'WHERE',
    'ALL' : '*',
    'GROUP_BY' : 'GROUP BY',
    'JOIN' : 'JOIN',
    'ON' : 'ON',
    'DISTINCT' : 'DISTINCT',
    'COUNT' : 'COUNT',
    'INSERT_INTO' : 'INSERT INTO',
    'VALUES' : 'VALUES',
    'UPDATE' : 'UPDATE',
    'SET' : 'SET',
    'DELETE_FROM' : 'DELETE FROM',
    'ORDER_BY' : 'ORDER BY',
    'LIMIT' : 'LIMIT',
    'HAVING' : 'HAVING',
    'EXISTS' : 'EXISTS',
    'IN' : 'IN',
    'BETWEEN' : 'BETWEEN',
    'LIKE' : 'LIKE',
    'IS_NULL' : 'IS NULL', 
    'ALTER_TABLE' : 'ALTER TABLE',
    'ADD_COLUMN' : 'ADD COLUMN',
    'DROP_COLUMN' : 'DROP COLUMN',
    'CREATE_TABLE' : 'CREATE TABLE',
    'DROP_TABLE' : 'DROP TABLE',
    'DEFAULT' : 'DEFAULT',
    'UNIQUE' : 'UNIQUE',
    'PRIMARY_KEY' : 'PRIMARY KEY',
    'FOREIGN_KEY' : 'FOREIGN KEY',
    'NOT_NULL' : 'NOT NULL',
    'CAST' : 'CAST',
#SPANISH RESERVED WORDS
    "TRAEME" : "TRAEME" ,
    "DE_LA_TABLA" : "DE LA TABLA",
    "DONDE" : "DONDE",
    "AGRUPANDO_POR" : "AGRUPANDO POR",
    "MEZCLANDO" : "MEZCLANDO",
    "EN" : "EN",
    "LOS_DISTINTOS" : "LOS DISTINTOS",
    "CONTANDO" : "CONTANDO",
    "METE_EN" : "METE EN",
    "LOS_VALORES" : "LOS VALORES",
    "ACTUALIZA" : "ACTUALIZA",
    "SETEA" : "SETEA",
    "BORRA_DE_LA" : "BORRA DE LA",
    "ORDENA_POR" : "ORDENA POR",
    "COMO_MUCHO" : "COMO MUCHO",
    "WHERE_DEL_GROUP_BY" : "WHERE DEL GROUP BY",
    "EXISTE" : "EXISTE",
    "EN_ESTO" : "EN ESTO",
    "ENTRE" : "ENTRE",
    "PARECIDO_A" : "PARECIDO A",
    "ES_NULO" : "ES NULO",
    "CAMBIA_LA_TABLA" : "CAMBIA LA TABLA",
    "AGREGA_LA_COLUMNA" : "AGREGA LA COLUMNA",
    "ELIMINA_LA_COLUMNA" : "ELIMINA LA COLUMNA",
    "CREA_LA_TABLA" : "CREA LA TABLA",
    "TIRA_LA_TABLA" : "TIRA LA TABLA",
    "POR_DEFECTO" : "POR DEFECTO",
    "UNICO" : "UNICO",
    "CLAVE_PRIMA" : "CLAVE PRIMA",
    "CLAVE_REFERENTE" : "CLAVE REFERENTE",
    "NO_NULO" : "NO NULO",
    "TRANSFORMA_A" : "TRANSFORMA A",
    'TODO' : 'TODO',
    "AGRUPANDO" : "AGRUPANDO",
    "POR" : "POR",
    "LOS" : "LOS",
    "DISTINTOS" : "DISTINTOS",
    "METE" : "METE",
    "EN" : "EN",
    "VALORES" : "VALORES",
    "ORDENA" : "ORDENA",
    "COMO" : "COMO",
    "MUCHO" : "MUCHO",
    "ESTO" : "ESTO",
    "PARECIDO" : "PARECIDO",
    "A" : "A",
    "ES" : "ES",
    "NULO" : "NULO",
    "DEFECTO" : "DEFECTO",
    "CLAVE" : "CLAVE",
    "PRIMA" : "PRIMA",
    "REFERENTE" : "REFERENTE",
    "NO" : "NO",
    "TRANSFORMA" : "TRANSFORMA",
    "DE" : "DE",
    "LA" : "LA",
    "TABLA" : "TABLA",
    "BORRA" : "BORRA",
    "CAMBIA" : "CAMBIA",
    "AGREGA" : "AGREGA",
    "COLUMNA" : "COLUMNA",
    "ELIMINA" : "ELIMINA",
    "CREA" : "CREA",
    "TIRA" : "TIRA",
    "DEL" : "DEL",
    "GROUP" : "GROUP",
    "BY" : "BY"
}